### ISSUE TITLE
Injection reworking

### ISSUE THREAD

**Issue by guybedford** [jspm/jspm#158]
Basically a workflow where you don't have a separate `importmap.json` _at all_, so that this workflow is additive.

So if you don't want, you can just run import package management directly inside of the HTML.

We did previously, but moved away from it with the inject functionality, but if we can reunify that does still provide a nice workflow.... where either separate `importmap.json` is being used.

* `jspm install` / `jspm uninstall` can all operate on import maps in HTML files (`-m app.html` for changing the input source of truth, and `-o out.html` for changing the output source of truth). (install traces the pins / top-level imports). By default `-m` changes both the input map and the output map to the provided map (which defaults to `importmap.json`). The output map can be changed via `-o`, and as soon as this is done, we move from tracing pins to not tracing pins (top-level imports in the import map).
* `jspm link` replaces `jspm extract` and `jspm inject`. And does this by:
  * `jspm extract` becomes `jspm link app.js -o outputmap.json`. That is, the act of adding an outputmap, moves from a pin trace to not tracing those pins, so it becomes a pruning extraction.
  * `jspm inject` then follows the same rule - `jspm link test.html` works by default - that is we extend link to support HTML tracing as well as JS tracing, as another trace target.
  * `jspm link test.html` does not alter `test.html`, instead it just updates `importmap.json` with the mappings.
  * `jspm link test.html test.js app` can link multiple things and update the `importmap.json`
  * `jspm link test.html test.js app -o out.json` would perform an extraction only providing the minimal map for the linkage.

Then inject can be replaced with the new workflows:
* `jspm install react -m test.html` would replace the inject package installer
* `jspm link test.html -m test.html` would replace the traditional `jspm link test.html`, but we can give it a sugar syntax - `jspm link -m test.html` where by default if the input map is an HTML file it will trace that HTML file as if you did `jspm link test.html -m test.html`

Then `jspm inject` and `jspm extract` can be fully removed.

**Comment by Bubblyworld** [comment]
I like the idea of a simpler, more powerful primitive a lot. Less is more 😄 some things I'm wondering about:

1. It's not super clear what `jspm link` takes as arguments. So `jspm install` takes a package specifier, which makes sense since in this case it's behaving as a package manager (similar behaviour to `npm install`). On the other hand, I feel like `jspm link <blah>` should take a module specifier (or at least something that resolves like one), since it's basically saying "I want to be able to `import "<blah>"` in my code, link the necessary dependencies for me". But in that case, `jspm link test.html` has some ambiguity - technically it would then resolve to a `test.html` package, not the local file `test.html`, right? You could write a relative URL like `jspm link ./test.html`, I guess, but this sort of thing looks like a tripwire.

2. I think the rule should be "trace top level pins if the output map is the same as the input map", rather than "trace top level pins unless the -o flag was provided". This way things like `jspm link app.js -m map.json` and `jspm link app.js -m map.json -o map.json`, which look like they should have the same behaviour, actually do have the same behaviour (tracing top level pins in both cases).

I think (1) is tricky from a UX point of view because you want to support local dev workflows, but also workflows where you need to link against modules coming from an external CDN, right? We could do a fallback to checking if there's a file in the `baseUrl` matching the specifier, but then someone goes and publishes `app.js` on npm and your workflow suddenly breaks for no apparent reason...

**Comment by Bubblyworld** [comment]
`jspm link`: handle own names and imports, files, also allow remote URL, don't allow arbitrary module specs (i.e. point to resource)
`jspm install`: handle package targets, like it currently does
